name: Alist Public Test
on: [workflow_dispatch]

jobs:
  deploy-alist:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Environment
      run: |
        # 安装系统工具
        sudo apt-get update && sudo apt-get install -y jq curl
        
        # 安装 Alist
        curl -fsSL "https://alist.nn.ci/v3.sh" | bash -s install
        
        # 生成访问凭证
        ./alist admin random | grep -oP 'password: \K.*' > cred.txt

    - name: Get Network Info
      run: |
        echo "=== 服务器公网IP ==="
        curl -4 icanhazip.com
        
        echo "\n=== 开放端口检测 ==="
        sudo lsof -i :5244 || echo "端口未监听"

    - name: Expose Service
      timeout-minutes: 360  # 最大运行时长
      run: |
        # 启动 Alist 服务
        ./alist server --data /tmp/alist_data &
        
        # 保持服务运行
        while true; do sleep 300; done

    - name: Output Info
      run: |
        echo "Alist 管理密码: $(cat cred.txt)"
        echo "访问端点: http://localhost:5244"
        echo "GitHub Runner IP: $(curl -s icanhazip.com)"
