name: Alist Public Test
on: [workflow_dispatch]

jobs:
  deploy-alist:
    runs-on: ubuntu-latest
    env:
      ALIST_DATA_DIR: /tmp/alist_data
    
    steps:
    # 系统环境准备
    - name: Setup Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl wget
        mkdir -p $ALIST_DATA_DIR
        
    # Alist 安装阶段 [1,5](@ref)
    - name: Install Alist
      run: |
        curl -fsSL "https://alist.nn.ci/v3.sh" | sudo bash -s install
        sudo chmod +x /usr/bin/alist
        
    # 服务启动阶段
    - name: Start Alist Service
      run: |
        nohup sudo alist server --data $ALIST_DATA_DIR > alist.log 2>&1 &
        sleep 10  # 等待服务启动
        
    # 系统信息采集 [2,6](@ref)
    - name: Get Server Info
      run: |
        echo "=== 存储空间 ==="
        df -h
        echo "\n=== 内存信息 ==="
        free -m
        echo "\n=== CPU 信息 ==="
        lscpu | grep -E 'Model name|Architecture'
        echo "\n=== 公网地址 ==="
        curl -4 icanhazip.com
        
    # 访问信息输出
    - name: Show Access Info
      run: |
        echo "Alist 管理密码：$(sudo alist admin | grep -oP 'password: \K.*')"
        echo "本地访问地址：http://localhost:5244"
        echo "运行日志："
        tail -n 20 alist.log
